### ISSUE TITLE
Configure Kibana URL. 

### ISSUE THREAD

**Issue by ashishxooa** [hyperledger-labs/blockchain-analyzer#35] opened 2019-12-02 05:05 UTC
Hi, 

I have been trying to use this project with my existing elasticsearch and kibana setup. Fabric beat is however not reading the kibana configurations. I did try many things but it always always connects to localhost. 
`2019-12-02T05:02:07.902Z	INFO	kibana/client.go:117	Kibana url: http://localhost:5601
`

Did config in fabricbeat.yml as mentioned in the readme and also in many other places still always localhost. Did anyone try with external kibana for this project?

**Comment by balazsprehoda** [comment] 2019-12-02 16:36
I think the cause of this issue is a missing configuration in fabricbeat.yml. Add your configuration here as
```
setup.kibana:
  host: "yourhost:yourport"
```
Sorry for bad docs. We have not tested this project with external Kibana or Elasticsearch servers yet.

**Comment by balazsprehoda** [comment] 2020-02-18 11:45
@ashishxooa did you manage to solve your problem?

**Comment by ashish235** [comment] 2020-02-18 11:51
@balazsprehoda thanks for following-up. I think it did, but there were some other issues, which I don't remember now. I gave up on this and would pick it up later. You might want to close the issue for now.

**Comment by balazsprehoda** [comment] 2020-02-18 11:55
@ashishxooa We have released a containerized version of fabricbeat to make it easier to deploy. I suggest you to try that when you pick it up again. For details, see #37

**Closed by balazsprehoda** 2020-02-18 11:55 UTC
